src/main/java/net/atos/entng/calendar/Calendar.java, src/main/java/net/atos/entng/calendar/controllers/CalendarController.java, src/main/java/net/atos/entng/calendar/event/CalendarRepositoryEvents.java, src/main/java/net/atos/entng/calendar/services/CalendarService.java, src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/test/java/net/atos/entng/calendar/services/CalendarServiceImplTest.java
Quand l'utilisateur accède à la page 'Calendrier':
- on vérifie si il possède un agenda par défaut
- si il n'en possède pas, on crée un agenda par défaut "Mon agenda"
2 tests unitaires (1 par fonction)
=> feat(form): #MC-1 add default agenda to all users

src/main/java/net/atos/entng/calendar/controllers/CalendarController.java, src/main/java/net/atos/entng/calendar/services/CalendarService.java, src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/sass/global/components/_index.scss, src/main/resources/public/sass/global/components/toasts.scss, src/main/resources/public/template/main-view.html, src/main/resources/public/ts/controllers/controller.ts, src/main/resources/public/ts/model/__tests__/calendar.test.ts, src/test/java/net/atos/entng/calendar/services/CalendarServiceImplTest.java
- le bouton 'supprimer' n'apparait pas quand le calendrier sélectionné est le calendrier par défaut
- si un appel au back est quand même effectué, on renvoie une HTTP 403 et un toast s'affiche pour prévenir l'utilisateur que le calendrier par défaut ne peut pas être supprimé
- message d'erreur si il y a une erreur autre durant la supression
- tests unitaires back+front
=> feat(form): #MC-3 remove 'delete' button for default calendar

src/main/java/net/atos/entng/calendar/Calendar.java, src/main/java/net/atos/entng/calendar/controllers/CalendarController.java, src/main/java/net/atos/entng/calendar/controllers/EventController.java, src/main/java/net/atos/entng/calendar/helpers/EventHelper.java, src/main/java/net/atos/entng/calendar/helpers/FutureHelper.java, src/main/java/net/atos/entng/calendar/helpers/UserHelper.java, src/main/java/net/atos/entng/calendar/models/User.java, src/main/java/net/atos/entng/calendar/security/ShareEventConf.java, src/main/java/net/atos/entng/calendar/services/EventServiceMongo.java, src/main/java/net/atos/entng/calendar/services/ServiceFactory.java, src/main/java/net/atos/entng/calendar/services/UserService.java, src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java, src/main/java/net/atos/entng/calendar/services/impl/DefaultUserServiceImpl.java, src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/edit-event.html, src/main/resources/public/template/main-view.html, src/main/resources/public/ts/behaviours.ts, src/main/resources/public/ts/controllers/controller.ts, src/main/resources/public/ts/model/CalendarEvent.ts, src/main/resources/public/ts/model/__tests__/calendar-event.test.ts, src/test/java/net/atos/entng/calendar/services/CalendarServiceImplTest.java
- Un utilisateur peut partager un évènement en utilisant le share-panel d'ODE
-  Choix de conception:
-  [Faisabilité]: il n'est pas possible de restreindre le partage d'un évènement au sein d'un groupe
- si on partage un évènement E d'un calendrier C avec un utilisateur avec qui C est déjà partagé, il ne se passe rien puisqu'il a déjà accès à l'évènement.
- Bouton 'Enregister et partager' (accessible depuis la vue d'édition de l'évènement)
- Bouton 'Partager' (accessible depuis la vue de liste de l'évènement, disparait quand plus d'un évènement est sélectionné)
- Il n'est pas possible de partager un calendrier par défaut (front)
=> feat(share): #MC-2 allow to share events

src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
Case where the event has been shared before but is not anymore:
any user with access to the event's calendar will also have access to the event
=> fix(form): #MC-18 if event is unshared, everyone has access to it

src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/edit-event.html, src/main/resources/public/ts/controllers/controller.ts
Dynamic function that changes the name of the share button depending on the calendars the event is in.
Creating/Editing an event that is in at least one shared calendar:
Button name = "Enregistrer et restreindre"
Creating/Editing an event that is in non-shared calendar(s) :
Button name = "Enregistrer et partager"
Button changes during creation depending on the selected calendars
=> feat(form): #MC-31 change share button name depending on calendar shared or not

src/main/resources/public/sass/global/components/calendar.scss, src/main/resources/public/sass/global/components/fixCalendar.scss, src/main/resources/public/sass/global/components/sidebar.scss
replace calendar & calendar icon
put 'ent blue' in place of all the other blues used
center timeslot buttons
replace list view dates & timepickers
=> fix(view): #MC-5 place calendar and calendar icon

src/main/resources/public/sass/global/components/_edit-event.scss, src/main/resources/public/sass/global/components/_index.scss, src/main/resources/public/template/edit-event.html
-La partie 'fin' du formulaire de récurrence est décalée sur la droite
-Quand on est en mode 'tous les jours' l'espace normalement réservé aux semaines reste mais est vide afin de laisser de la place pour afficher le calendrier.
=> fix(form): #MC-19 access end-of-recurrence calendar

src/main/resources/public/template/read-calendar.html, src/main/resources/public/ts/controllers/controller.ts
When creating an event by clicking on the calendar, 2 lightboxes appeared (one outside the calendar directive, one inside).
--> calendar was more highlighted than the rest of the background when the lightbox appeared.
Fix is so that the lightbox external to the calendar will not appear.
=> fix(view): #MC-22 fix create event view

src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/edit-event.html, src/main/resources/public/template/main-view.html, src/main/resources/public/ts/controllers/controller.ts
- share button disappears if event is recurrent
- if event is not recurrent: button is named 'restrict' if its calendar is shared, 'shared' if not
=> fix(share): #MC-39 restrict share button in list view

src/main/resources/public/template/edit-event.html, src/main/resources/public/ts/controllers/controller.ts
Warning is reset to pristine when a form is closed without having been saved
=> fix(view): MC-41 deactivate empty title warning

package.json, src/main/resources/public/template/main-view.html, src/main/resources/public/ts/controllers/controller.ts, src/main/resources/public/ts/directives/side-bar/side-bar.html, src/main/resources/public/ts/directives/side-bar/side-bar.ts
On closing of the share-panel/calendar edition panel:
- update of all the calendars (selected calendar is unselected by default)
- selected calendar is selected again 
method hideOtherCalendarCheckboxes is triggered using rxjs
=> fix(calendar): #MC-55 update calendar after sharing it

src/main/java/net/atos/entng/calendar/helpers/EventHelper.java, src/main/java/net/atos/entng/calendar/utils/DateUtils.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/edit-event.html, src/main/resources/public/ts/controllers/controller.ts, src/main/resources/public/ts/core/const/date-format.ts, src/main/resources/public/ts/model/CalendarEvent.ts, src/main/resources/public/ts/model/constantes/actions.const.ts, src/main/resources/public/ts/utils/multiDaysEventsUtils.ts
Les évènements peuvent durer plusieurs jours:
- ils sont affichés comme étant des créneaux de 7h à 20h sur le calendrier (vue calendaire) :  création de sous-évènements dans le front (contenant un champ isMultiDayPart = true)
- restauration des évènements entiers pour la vue liste
- création d'un fichier d'utils pour séparer un évènement en sous évènements
- un évènement récurrent ne peut pas avoir une longueur supérieure à celle de la récurrence
- un évènement sur plusieurs jours ne peut avoir qu'une récurrence hebdomadaire
- pour la récurrence, si la date de fin de récurrence se trouve entre le début et la fin de l'évènement sur plusieurs jours, il sera quand même enregistré
=> feat(event): #MC-8 add multiple days events possibility

src/main/resources/public/ts/controllers/controller.ts
Bug : calendars with same name were both selected when creating an event.
Solved by using a calendar array instead of a string array with the ODE's multi-combo component.
Same behaviour as in dairy
=> fix(form): #MC-53 solve calendars with same name bug

src/main/resources/public/ts/controllers/controller.ts
Problem : when accessing the calendar page for the first time, no calendar is selected and the calendar timetable therefore does not appear.
Solution : Selecting the default calendar specifically when loading the page
=> fix(calendar) : #MC-51 select default calendar automatically when loading page

src/main/java/net/atos/entng/calendar/controllers/EventController.java, src/main/java/net/atos/entng/calendar/core/constants/Field.java, src/main/java/net/atos/entng/calendar/helpers/EventHelper.java, src/main/java/net/atos/entng/calendar/services/EventServiceMongo.java, src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java, src/main/resources/i18n/fr.json, src/main/resources/public/ts/controllers/controller.ts, src/main/resources/public/ts/core/enum/period-type.enum.ts, src/main/resources/public/ts/model/Calendar.ts, src/main/resources/public/ts/model/CalendarEvent.ts, src/main/resources/public/ts/services/calendar-event.service.ts, src/main/resources/public/ts/services/calendar.service.ts, src/main/resources/public/ts/services/index.ts, src/test/java/net/atos/entng/calendar/services/EventServiceMongoImplTest.java
Adding a lazy loading in order to upload events at every view change instead of uploading all events and calendars at the beginning
Improve performances
**_Second commit is only here to deploy on Jenkins_**
**Fichier controller.ts** 
Lignes changements effectués :
- 85-96
- 109-113
- 121-123
- 136-137
- 153-170
- 579
- 1708-1717
- 173-1737
fix(performance): #MC-69 lazy loading to fetch events
https://entsupport.gdapublic.fr/secure/RapidBoard.jspa?rapidView=99&projectKey=MC&view=detail&selectedIssue=MC-69&sprint=658
=> fix(performance): #MC-69 lazy loading to fetch events

src/main/resources/public/template/edit-event.html
fix MC-135 https://github.com/OPEN-ENT-NG/calendar/pull/81
Recurrence section does not appear in form if event already has booking
Change is only the last line
see MC-135 (will be merged together after PR is approved)
Create event with booking, save it, and open it to check if the recurrence section has disappeared
#MC-135 https://entsupport.gdapublic.fr/browse/MC-135
=> fix(recurrence): #MC-135 forbid recurrence addition to event with booking

src/main/java/net/atos/entng/calendar/helpers/RbsHelper.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/main-view.html, src/main/resources/public/ts/controllers/controller.ts, src/main/resources/public/ts/directives/rbs-booking-delete-info/rbs-booking-delete-info.html, src/main/resources/public/ts/directives/rbs-booking-delete-info/rbs-booking-delete-info.ts, src/main/resources/public/ts/model/CalendarEvent.ts, src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
display message to request choice from user when deleting event with booking : they can delete event only or delete the associated booking additionally. (see tests)
calendar view : click on created event with booking and delete it, the message with choice appears in the confirmation popup
list view: 
- try to delete one event without booking : behaviour is same as before
- try to delete one event with booking : behaviour is same as calendar view + the event edition window opens
- try to delete many events including one with booking: message states that the deletion will not impact [[event with booking's name]]'s booking.
#MC-123 https://entsupport.gdapublic.fr/browse/MC-123
=> feat(delete): #MC-123 display booking deletion checkbox

src/main/java/net/atos/entng/calendar/ical/ICalHandler.java, src/test/java/net/atos/entng/calendar/ical/ICalHandlerTest.java
all day imported events are saved from 5:00 utc (7:00 fr) to 18:00 utc (20:00 fr) (same flow as all day avents created within the module)
when all day events are exported they are from day1 00:00 utc to dayN+1 00:00.
import calendar with all day events (linked in ticket)
check dates in month and day view
export the same calendar and check dates again
#MC-139 https://entsupport.gdapublic.fr/browse/MC-139
=> fix(imports): #MC-139 fix timezone hour offset

src/main/java/net/atos/entng/calendar/ical/ICalHandler.java
=> fix(imports): #MC-149 fix special character when importing calendar

src/main/resources/public/sass/global/components/calendar.scss, src/main/resources/public/ts/controllers/controller.ts
User cannot create event by clicking on month view calendar (same behaviour as presences cdt and rbs)
try to create event by clicking on number in month view
check that the mouse does not change
#MC-142 https://entsupport.gdapublic.fr/browse/MC-142
=> fix(calendar): #MC-142 remove month view event creation possibility

src/main/resources/public/template/edit-event.html, src/main/resources/public/template/view-event.html, src/main/resources/public/ts/controllers/controller.ts, src/main/resources/public/ts/core/const/rbs-sniplet.const.ts, src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
the two instances of the sniplet are initialized at the same time as the module but when one is displayed information is sent to the opened sniplet
check ng2 console and network when using sniplet (changing date/resource type ...)
#MC-122 https://entsupport.gdapublic.fr/browse/MC-122
=> fix(sniplet): #MC-122 fix sniplet surplus calls

src/main/resources/public/ts/controllers/controller.ts
cancel is now working for calendar modification
Use updateCalendars to force update of the selected calendar and have informations before modifications and cancel.
☑︎ Restore the color of calendar before the start of modification
☑︎ Restore the right information of your calendar in modification view when you go again in it after cancel the modification
https://entsupport.gdapublic.fr/browse/MC-46
=> fix(calendar): #MC-46 restore right calendar's informations after cancel the modification

src/main/resources/public/ts/directives/calendar-item/calendar-item.html, src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
when clicking in sync button it does not (un)select the calendar anymore
click on sync button
#MC-203 https://jira.support-ent.fr/browse/MC-203
=> fix(sync): #MC-203 keep calendar selected when clicking on sync button

deployment/calendar/conf.json.template, src/main/java/net/atos/entng/calendar/Calendar.java, src/main/java/net/atos/entng/calendar/controllers/CalendarController.java, src/main/java/net/atos/entng/calendar/core/constants/Field.java, src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
There is a minimum time (in seconds) between two syncs, which can be set in the config.
If the minimum time has not passed, the sync does not take place.
/!\ Config must change:
```
{
"name": "net.atos~calendar~2.5.0",
"config": {
...
"calendarSyncTTL": ${calendarSyncTTL}
}
...
}
```
Try to sync two times in a row using postman, second time should not update calendar and events.
[MC-210](https://jira.support-ent.fr/browse/MC-210)
=> feat(sync): #MC-210 add time to live for update

src/main/resources/public/sass/global/components/_icons.scss, src/main/resources/public/sass/global/components/sidebar.scss, src/main/resources/public/ts/directives/calendar-item/calendar-item.html, src/main/resources/public/ts/directives/calendar-item/calendar-item.ts, src/main/resources/public/ts/services/calendar.service.ts
Add loader when calendar is updated (icon becomes sync again when calendar is updated).
External calendar is updated on first arrival on the page/reload of the page + when sync icon is clicked.
First update check after 15s, then every minute
load calendar page. check that all calendars are loading and if the loading stops.
check the same after clicking on the sync button of one calendar.
[MC-220](https://jira.support-ent.fr/browse/MC-220)
=> feat(sync): #MC-220 handle external calendar sync waiting

src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
update toaster only appears after click on sync button
reload page, then sync calendars, toasters should appear if the sync button has been clicked only
[MC-249](https://jira.support-ent.fr/browse/MC-249)
=> fix(toasts): #MC-249 fix toasts appearance case

src/main/resources/public/sass/global/components/sidebar.scss
loader icon does not disapear when calendar is not selected + mouse is not on calendar
unselect calendar and click on sync icon, then see if loader appears
[MC-248](https://jira.support-ent.fr/browse/MC-248)
=> fix(icon): #MC-248 show loader if calendar is not selected

src/main/resources/public/ts/directives/side-bar/side-bar.html
when external calendar rights are disabled, external calendar's empty state message no longer appears
Disable rights on account with no external calendars and check sidebar. Nothing from external calendar category should appear.
Enable rights and check if title + empty state message appear.
[MC-282](https://jira.support-ent.fr/browse/MC-282)
=> fix(sidebar): #MC-282 remove empty message when no external calendar rights

build.gradle, gradle.properties, src/main/java/net/atos/entng/calendar/Calendar.java, src/main/java/net/atos/entng/calendar/controllers/CalendarController.java, src/main/java/net/atos/entng/calendar/core/enums/ErrorEnum.java, src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java, src/main/java/net/atos/entng/calendar/helpers/IModelHelper.java, src/main/java/net/atos/entng/calendar/helpers/PlatformHelper.java, src/main/java/net/atos/entng/calendar/helpers/StringsHelper.java, src/main/java/net/atos/entng/calendar/ical/ICalHandler.java, src/main/java/net/atos/entng/calendar/models/CalendarModel.java, src/main/java/net/atos/entng/calendar/models/IModel.java, src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java, src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java, src/main/resources/public/ts/directives/calendar-item/calendar-item.ts, src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.html, src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts, src/main/resources/public/ts/utils/externalCalendarUtils.ts, src/test/java/net/atos/entng/calendar/helper/IModelHelperTest.java, src/test/java/net/atos/entng/calendar/helper/PlatformHelperTest.java
- can only create 1 calendar of each external platform
- front loader stops when eb from zimbra is received
- ical parsing fixed
for both platform and link external calendar:
- create calendar
- update calendar
then :
- sync calendars
- try to create 2nd Zimbra calendar
[MC-285](https://jira.support-ent.fr/browse/MC-285)
=> fix(external): #MC-285 fix external calendar flow

src/main/java/net/atos/entng/calendar/core/enums/ErrorEnum.java, src/main/java/net/atos/entng/calendar/ical/ICalHandler.java, src/test/java/net/atos/entng/calendar/ical/ICalHandlerTest.java
Calendar import does not produce invalid events (events with end date before start date) anymore.
Will be delivered with the following request:
```
db.getCollection('calendarevent').remove({"$expr" : {"$gte" :["$startMoment", "$endMoment"]}})
```
import the ics present in the ticket, two events should appear (YYYY/MM/DD french time) : 
2023/07/08 from 7:00 to 20:00
2023/05/22 from 7:00 to 20:00
[Zone-C-test.txt](https://github.com/OPEN-ENT-NG/calendar/files/11935175/Zone-C-test.txt)
[MC-284](https://jira.support-ent.fr/browse/MC-284)
=> fix(import): #MC-284 fix one day event import

src/main/resources/public/ts/controllers/controller.ts
Update external calendar events with startDate startig at first day of the selected view (day, week or month) instead of strating at the current day.
MC-294 : https://jira.support-ent.fr/browse/MC-294
=> fix(sync): #MC-294 fix events hiding on external calendar sync

src/main/java/net/atos/entng/calendar/core/constants/Field.java, src/main/java/net/atos/entng/calendar/helpers/EventHelper.java, src/main/java/net/atos/entng/calendar/utils/DateUtils.java, src/main/resources/i18n/en.json, src/main/resources/i18n/fr.json, src/main/resources/public/template/edit-event.html, src/main/resources/public/ts/controllers/controller.ts, src/main/resources/public/ts/model/constantes/TIME.ts
To prevent user from saving too long events and slow down the application, we now display a message and disable save button if the start date of event is too old (before january 1, 2000) or end date is more than in 80 years.
Create a new event and choose a date before 01 01 2000 or a end date after 2103
[MC-297](https://jira.support-ent.fr/browse/MC-297)
=> fix(calendarEvent): #MC-297 disable save button when too old start date and too far end date

src/main/java/net/atos/entng/calendar/helpers/EventHelper.java, src/main/java/net/atos/entng/calendar/services/impl/DefaultUserServiceImpl.java, src/test/java/net/atos/entng/calendar/services/DefaultUserServiceImplTest.java
Suppression de "UNION MATCH" non nécessaires et ralentissant fortement la requête.
Non nécessaires car les groupes ciblés par ces "UNION MATCH" sont des sous-ensembles du label "Group".
On peut donc les retirer pour soulager la requête sans changer le nombre et la nature des résultats retournés.
Testé en préprod sur un cas de requête lente : 
https://edifice-community.atlassian.net/browse/WB-3307
=> fix: WB-3307, improve searching users from groups 
