- src/main/resources/public/template/edit-event.html
- src/main/resources/public/template/events-list.html
- src/main/resources/public/ts/controllers/controller.ts
Correction impossibilité de supprimer un événement et mise à jour des droits concernant les événements des agendas partagés
> fix: CO-866 Correct deletion calendar event and rights shared calendars

- .gitignore
- deployment/calendar/migration/1.9.2/changeTypeCalendarInCalendarEvent.js
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/sass/global/components/additional.scss
- src/main/resources/public/sass/global/components/calendar.scss
- src/main/resources/public/template/edit-event.html
- src/main/resources/public/template/events-list.html
- src/main/resources/public/template/main-view.html
- src/main/resources/public/template/view-event.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/directives/formatInputTime.ts
- src/main/resources/public/ts/model/Calendar.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
Change the attribute calendar of a calendarEvent into an array to allow the selection of several calendars when an event is created + Include edit remove recurrence
> [NGSM-267] Change the attribute calendar of a calendarEvent + Include edit remove recurrence

- src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
-Default calendar name is  'Calendar Lastname Firstname'
> fix(form): #MC-1 add default agenda to all users

- src/test/java/net/atos/entng/calendar/services/DefaultUserServiceImplTest.java
Unit Test for #15  (fetchUsers method)
> test(share): #MC-2 add share API background Unit Test

- src/main/resources/public/template/main-view.html
- src/main/resources/public/template/top-menu.html
'Create calendar' and 'Create event' buttons are moved to the top right side of the screen, above the week number.
> feat(form): #MC-4 Replace calendar and event creation buttons

- src/main/resources/public/template/top-menu.html
Create calendar then create event instead of create event and then create calendar
> fix(form): #MC-4 switch creation buttons places

- src/main/resources/i18n/fr.json
- src/main/resources/public/template/edit-event.html
- src/main/resources/public/ts/behaviours.ts
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/constantes/RIGHTS.ts
- src/main/resources/public/ts/model/constantes/index.ts
User with 'read' rights will access the 'view event' panel only.
User with 'contrib' rights will have the 'save and share' button disabled on the edition panel.
> fix(form): #MC-14 solve editing rights issue on shared events

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
Change warning message when viewing an event without editing rights
> fix(form): #MC-14 change event view without edition warning

- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/view-src/notify/calendar/share.html
Creating an event: is the 'save and share' button is clicked, no notifications will appear
Editing an event:
- if the event is not shared, it works as usual (all the users with access to its shared calendar(s) will be notified)
- if the event is shared, only the owner of the calendar(s), owner of the event and people with access to the event will be notified
> fix(form): #MC-16 do not display notifications when no access to restricted event

- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
Notification appears when event shared in a default calendar is edited
> fix(form): #MC-16 notification appears for default calendars

- src/main/resources/public/ts/controllers/controller.ts
no console errors when loading the page
> fix(form): #MC-31 change share button name depending on calendar shared or not

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/sass/global/_calendar-specifics.scss
- src/main/resources/public/sass/global/_mixins.scss
- src/main/resources/public/sass/global/components/_index.scss
- src/main/resources/public/sass/global/components/sidebar.scss
- src/main/resources/public/template/main-view.html
- src/main/resources/public/template/top-menu.html
- src/main/resources/public/ts/app.ts
- src/main/resources/public/ts/behaviours.ts
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/core/const/roots.ts
- src/main/resources/public/ts/directives/index.ts
- src/main/resources/public/ts/directives/side-bar/side-bar.html
- src/main/resources/public/ts/directives/side-bar/side-bar.ts
Directive with:
-choice of view: calendar or list (list does not show, will be treated in another ticket)
-list of calendars
Modeled after the side bar from Diary (cahier de textes)
> feat(form): #MC-6 create directive with left calendar menu

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/events-list.html
Add empty state when the list view is selected but no events exist between the specified dates.
> feat(list): #MC-30 add empty state

- src/main/resources/public/template/edit-event.html
"remove recurrence" checkbox does not appear anymore when creating an event
> fix(form): #MC-21 remove recurrence supression option when creating an event

- src/main/resources/public/template/edit-event.html
- src/main/resources/public/ts/controllers/controller.ts
Date string is cropped to only show the date (AAAA-MM-DD)
> fix(form): #MC-20 remove letters after recurrence end date when viewing event

- src/main/resources/public/sass/global/components/calendar.scss
fix gap before input field in form
> fix(view): #MC-5 no space before inputs in form

- src/main/resources/public/ts/controllers/controller.ts
case  Modifier -> 'Cet évènement seulement' + 'Sortir cet évènement de la récurrence' + 'Supprimer les autres évènements de la récurrence': event is no more recurrent
> fix(recurrence): MC-36 fix end of recurrence on event

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/edit-event.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/constantes/actions.const.ts
- src/main/resources/public/ts/model/constantes/index.ts
If end time is before start time:
-'save' and 'save and share' buttons are disabled
-warning message under the hour section
> fix(view): MC-45 add error message when end time is before start time

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/ts/directives/side-bar/side-bar.html
"Mes agendas" ==> "Agendas disponibles"
> feat(view): MC-49 change title from calendar section in sidebar

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/sass/global/components/additional.scss
- src/main/resources/public/sass/global/components/calendar.scss
- src/main/resources/public/template/tooltip-template.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/Utils.ts
Basé sur le tooltip du module Emploi du Temps
La couleur du titre change en fonction de la couleur de l'agenda
UPDATE: couleurs OK pour toutes les couleurs possibles de l'agenda
> feat(view): #MC-11 display tooltip when mouse is over an event

- src/main/resources/public/ts/directives/side-bar/side-bar.ts
link directive scope.calendar with module scope.calendar
> fix(calendar): MC-52 reset calendar when calendar is selected + unselected in directive

- src/main/resources/public/ts/controllers/controller.ts
Edition d'event seul lors d'une récurrence :
sortir l'event de la récurrence + supprimer le reste de la récurrence ==> griser le btn supprimer, dégriser le btn enregistrer (enregistre + supprime le reste de la récurrence)
> fix(form): MC-56 change recurrence edition use case

- src/main/resources/public/ts/directives/side-bar/side-bar.ts
Fix suite à une régression engendrée par la MC-52
> fix(sidebar): MC-58 fix regression on list and calendar icon

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/sass/global/_mixins.scss
- src/main/resources/public/sass/global/components/sidebar.scss
- src/main/resources/public/ts/directives/side-bar/side-bar.html
Basé sur un tooltip déjà existant sur Présences
> feat(view): MC-33 add tooltip to show shared calendar creator

- src/main/resources/public/ts/controllers/controller.ts
features corrected:
- edition of 1 event of the recurrence generates a warning and is not saved
- recurrence of 3 events disappears when they are edited
> fix(recurrence): #MC-61 correct recurrence edition bug

- src/main/resources/view-src/notify/calendar/share.html
fix the share notification so that it fits version 4.0 of timeline (mustache implementation).
> fix(notification): #MC-62 update sharing notification for timeline

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/sass/global/components/calendar.scss
- src/main/resources/public/template/tooltip-template.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/core/enum/dayOfWeek.enum.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/public/ts/model/constantes/TIME.ts
- src/main/resources/public/ts/utils/date.utils.ts
- adapt tooltip to muliple days events
- add recurrence information
> fix(tooltip): #MC-54 edit tooltip information

- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/public/ts/utils/multiDaysEventsUtils.ts
Handle case where event start or end moments are not valid (Invalid Date/NaN/undefined ...)
- event does not appear in the front-end of the application
- use of the module goes on as usual
- security ensures that an event has valid start and end moments before saving it
> fix(dates): #MC-66 handle and secure invalid dates

- src/main/java/net/atos/entng/calendar/Calendar.java
- src/main/java/net/atos/entng/calendar/controllers/EventController.java
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/services/UserService.java
- src/main/java/net/atos/entng/calendar/services/impl/DefaultUserServiceImpl.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/sass/global/_mixins.scss
- src/main/resources/public/sass/global/components/_edit-event.scss
- src/main/resources/public/sass/global/components/_icons.scss
- src/main/resources/public/sass/global/components/_index.scss
- src/main/resources/public/template/edit-event.html
- src/main/resources/public/template/main-view.html
- src/main/resources/public/template/view-event.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/public/ts/services/attachment.service.ts
- src/main/resources/public/ts/services/index.ts
- src/test/java/net/atos/entng/calendar/services/DefaultUserServiceImplTest.java
- 'add attachments' button opens media library (linked with workspace) where user can upload and select documents
- attachments can be downloaded (condition: user is attachment owner OR has access to event)
- tooltip with attachment full name appears when mouse over attachment
> feat(event): #MC-7 add attachments to event

- src/main/resources/public/ts/controllers/controller.ts
Calendars already ordered alphabetically in #66
> fix(calendar) : #MC-59 select default calendar automatically when creating event

- src/main/resources/public/sass/global/components/calendar.scss
recover sidebar css after changes in commit 94411f7b975dd4c368b752567edb47f53d4168a6
> fix(sidebar) : #MC-67 recover sidebar css and delete orange border

- src/main/resources/public/sass/global/components/sidebar.scss
> fix(color): #MC-50 change opacity sidebar

- README.md
- deployment/calendar/conf.json.template
- src/main/java/net/atos/entng/calendar/Calendar.java
- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/controllers/EventController.java
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/helpers/FutureHelper.java
- src/main/java/net/atos/entng/calendar/helpers/RbsHelper.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/edit-event.html
- src/main/resources/public/template/main-view.html
- src/main/resources/public/template/read-calendar.html
- src/main/resources/public/template/view-event.html
- src/main/resources/public/ts/app.ts
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/core/const/date-format.ts
- src/main/resources/public/ts/directives/index.ts
- src/main/resources/public/ts/directives/rbs-booking-delete-info/rbs-booking-delete-info.html
- src/main/resources/public/ts/directives/rbs-booking-delete-info/rbs-booking-delete-info.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/public/ts/model/index.ts
- src/main/resources/public/ts/model/rbs/booking.model.ts
- src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
- src/main/resources/view-src/calendar.html
Sniplet allowing to make bookings in RBS from Calendar module
/!\ Config must change:
```
{
"name": "net.atos~calendar~2.3.0",
"config": {
...
"enable-rbs": ${enableRbs}
}
...
}
```
/!\ Platform config should have an addiional field if it uses RBS:
```
config {
...
enableRbs: true
}
```
see RBS-107 pull request https://github.com/OPEN-ENT-NG/rbs/pull/11
#MC-12 https://entsupport.gdapublic.fr/browse/MC-12
> feat(booking) : #MC-12 allow RBS booking from event form

- src/main/resources/public/ts/controllers/controller.ts
attachment changes are propagated to the entire recurrence when the "Edit all recurrence" option is selected
create a recurrence. edit it (select "Edit all recurrence") and add an attachment.
MC-115 https://entsupport.gdapublic.fr/browse/MC-115
> fix(recurrence): #MC-115 propagate attachments to all recurrence

- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/helpers/RbsHelper.java
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
Keep booking if event with booking becomes recurrent and the 1st day is the original day of the booking.
create an event with a booking, save it, open it and create a recurrence
MC-111 https://entsupport.gdapublic.fr/browse/MC-111
> fix(recurrence): #MC-111 handle recurrence created after booking

- src/main/resources/public/template/edit-event.html
Recurrence section does not appear in form if event already has booking
Create event with booking, save it, and open it to check if the recurrence section has disappeared
#MC-135 https://entsupport.gdapublic.fr/browse/MC-135
> fix(recurrence): #MC-135 forbid recurrence addition to event with booking

- src/main/resources/public/ts/directives/rbs-booking-delete-info/rbs-booking-delete-info.html
- src/main/resources/public/ts/model/rbs/booking.model.ts
- src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
Removed booking info if booking has been deleted
- create 2 events with bookings in Calendar Module
- go to RBS and delete one of the booking
- go to Calendar and try to delete the events (click on delete button and display popup)
- check that the booking info is not displayed for the event with the deleted booking
#MC-112 https://entsupport.gdapublic.fr/browse/MC-112
> fix(popup): #MC-112 remove booking info in deletion popup if booking has been deleted

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/main-view.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/directives/rbs-booking-delete-info/rbs-booking-delete-info.html
- src/main/resources/public/ts/directives/rbs-booking-delete-info/rbs-booking-delete-info.ts
- src/main/resources/public/ts/model/rbs/booking.model.ts
- src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
fix #83 :
- check booking deletion rights
- changes in popup appearance
for many cases (author, shared with RBS manage right, shared with no RBS right ...):
calendar view : click on created event with booking and delete it, the message with choice appears in the confirmation popup
list view:
try to delete one event without booking : behaviour is same as before
try to delete one event with booking : behaviour is same as calendar view + the event edition window opens
try to delete many events including one with booking: message states that the deletion will not impact [[event with booking's name]]'s booking.
#MC-123 https://entsupport.gdapublic.fr/browse/MC-123
> fix(delete): #MC-123 display booking deletion checkbox

- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/core/enums/RbsEventBusActions.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/helpers/FutureHelper.java
- src/main/java/net/atos/entng/calendar/helpers/RbsHelper.java
- src/main/java/net/atos/entng/calendar/services/EventServiceMongo.java
- src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/public/ts/services/calendar-event.service.ts
- delete bookings from event
- check rbs deletion rights before deleting the booking
try to delete bookings in the following cases:
- is booking creator
- is resource owner
- is ADML for the resource type's structure
- resource type was shared with validate or manag
#MC-147 https://entsupport.gdapublic.fr/browse/MC-147
> feat(rbs): #MC-147 secure deletion back-end

- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/helpers/RbsHelper.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
Send booking deletion response to calendar
create an event with booking
delete booking
deletebooking while selecting delete bookings option
#MC-125 https://entsupport.gdapublic.fr/browse/MC-125
> feat(rbs): #MC-125 handle booking deletion response

- src/main/resources/public/ts/controllers/controller.ts
debug calendar datepicker that did not work (MC-69 regression)
in week and day view: select another day with calendar datepicker and see if the change is correct
#MC-150 https://entsupport.gdapublic.fr/browse/MC-150
> fix(datepicker): #MC-150 debug hidden datepicker

- src/main/java/net/atos/entng/calendar/ical/ICalHandler.java
- src/main/java/net/atos/entng/calendar/utils/DateUtils.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/main-view.html
fix 2h offset when importing ical
import error will appear if ther is a problem on the time :
import ical and check events times.
Check if it works with and without the environment variable TZ: "Europe/Paris"
#MC-138 https://entsupport.gdapublic.fr/browse/MC-138
> fix(imports): #MC-138 fix hour change when importing ical

- src/main/java/net/atos/entng/calendar/ical/ICalHandler.java
fix 2h offset when exporting ical
export ical in other calendar and check events times.
Check if it works with and without the environment variable TZ: "Europe/Paris"
#MC-143 https://entsupport.gdapublic.fr/browse/MC-143
> fix(exports): #MC-143 fix hour change when exporting ical

- src/main/resources/public/template/events-list.html
Add empty state graphic when there are no events at all in calendar too. 
check adding of empty state when there are no events.
https://entsupport.gdapublic.fr/browse/MC-120
> feat(list): #MC-120 add empty state when no events

- src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
Change date format (DD-MM-YYYY HH:mm - DD-MM-YYYY HH:mm to DD/MM/YY HH:mm - HH:mm)
Before : 
After : 
Check change of date format
https://entsupport.gdapublic.fr/browse/MC-152
> feat(delete): #MC-152 change date format

- src/main/resources/public/template/tooltip-template.html
add location of the event in tooltip template 
check location in tooltip template 
https://entsupport.gdapublic.fr/browse/MC-144
> feat(calendar): #MC-144 add location in tooltip template

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
add in back a security to can't share default calendar
Test if the flow is the same than before
https://entsupport.gdapublic.fr/browse/MC-26
> feat(share): #MC-26 add back security to don't share default calendar

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/controllers/EventController.java
- src/main/java/net/atos/entng/calendar/core/constants/Actions.java
Providing a way to determine what exactly is happening with HTTP request, to diagnose unexpected or undesirable behavior.
To deal with this, we add API trace to trace HTTP request on specific routes.
Trace annotation contains two parameters :
value (String): Set action name
body (Boolean): Set if the request body should be saved(by default body takes true)
Create agenda in "http://localdev:8090/calendar#/"
check in mongodb using `db.getCollection('traces').find({"action":"CREATE_CALENDAR"})`
MC-161 : https://entsupport.gdapublic.fr/browse/MC-161
> feat(api): #MC-161 add trace to api

- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/core/enum/rbs/rbs-eventer.enum.ts
- src/main/resources/public/ts/model/rbs/rbs-emitter.model.ts
Module works when no conf is added
choose platform without enableRbs = true config, try to create event
#MC-164 https://entsupport.gdapublic.fr/browse/MC-164
> fix(rbs): #MC-164 secure rbs calls

- src/main/java/net/atos/entng/calendar/ical/ICalHandler.java
- src/test/java/net/atos/entng/calendar/ical/ICalHandlerTest.java
handle internet calendar imports with other timezones
import calendar attached to ticket
#MC-177 https://entsupport.gdapublic.fr/browse/MC-177
> fix(imports): #MC-177 fix internet calendar imports

- src/main/resources/public/template/main-view.html
display calendar title in delete calendar view which miss before 
create multiple events for many calendars
check with multiple events of many calendars if there are calendar's title for events
check with an event with multiple calendar
https://jira.support-ent.fr/browse/MC-72
> fix(list): #MC-72 display calendar title in delete calendar view

- .github/workflows/dev-check-repository.yml
- docker-compose.yml
> chore(node): upgrade node version docker

- build.sh
The issue contains the description : https://github.com/OPEN-ENT-NG/calendar/issues/110
Exception :
Entcore problem, what is displayed on the VM :
[This is most likely not a problem with npm itself.
In most cases you or one of your dependencies are requestion a package version that doesn't exist]
We can check by compiling the buildNode (./build.sh buildNode) in our module and according to our branch (if it is master or a branch that is part of the entcore or if it is a totally different branch)
110 :  https://github.com/OPEN-ENT-NG/calendar/issues/110
> fix(buildnode): #110 fix buildnode exception

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
In order to  to access the config of the module, we add an API endpoint.
Since there is no sensitive data in the configuration, we do not have to secure them.
In order to check our modifications, we just have to access the config in calendar
Issue-112 : https://github.com/OPEN-ENT-NG/calendar/issues/112
> fetch(config): #112 add routine to get config

- src/main/resources/public/template/tooltip-template.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/utils/__test__/date.utils.test.ts
- src/main/resources/public/ts/utils/date.utils.ts
add new display Date on tooltip-template
- check if the change of display is right (i would like add some screens but there is an error with github so i couldn't add screens)
https://jira.support-ent.fr/browse/MC-178
> feat(calendar): #MC-178 add new display Date

- src/main/resources/public/template/main-view.html
add calendar's info in delete pop up in calendar view
- check if calendar's infos was right 
- check if the calendar's info appear just for calendar view 
https://jira.support-ent.fr/browse/MC-83
> feat(calendar): #MC-83 add calendar's info in delete pop up in calendar view

- src/main/resources/public/template/main-view.html
display calendar title in delete calendar view
check if the infos was not display for recurrence view
https://jira.support-ent.fr/browse/MC-72
> fix(list): #MC-72bis display calendar title in delete calendar view

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/top-menu.html
- src/main/resources/public/ts/app.ts
- src/main/resources/public/ts/directives/calendar-item/calendar-item.html
- src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
- src/main/resources/public/ts/directives/side-bar/side-bar.html
- src/main/resources/public/ts/directives/side-bar/side-bar.ts
- src/main/resources/public/ts/model/Calendar.ts
-add "add external calendar" button
-add "external calendar" section in sidebar with new component for items
see if formentionned items appear
test sidebar new section :
- empty state if there are no calendars
- try to (un)select calendar
- try ton (un)check calendar checkboxes and use menu buttons (edit, ...)
#MC-165 https://jira.support-ent.fr/browse/MC-165
> feat(view): #MC-165 init external calendar import view

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/top-menu.html
- src/main/resources/public/ts/app.ts
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/core/enum/platform.enum.ts
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.html
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
- src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.html
- src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
- src/main/resources/public/ts/directives/index.ts
- src/main/resources/public/ts/model/Calendar.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/public/ts/model/calendar-form.model.ts
- src/main/resources/public/ts/services/calendar.service.ts
- create calendar import popup with its form rules
- create front-end endpoints for later use
try to open, fill and close the form
#MC-167 https://jira.support-ent.fr/browse/MC-167
> feat(view): #MC-167 add external calendar form

- gulpfile.js
- package.json
- src/main/resources/public/sass/global/_calendar-specifics.scss
- src/main/resources/public/sass/global/components/_icons.scss
- src/main/resources/public/sass/global/components/sidebar.scss
- src/main/resources/public/ts/directives/calendar-item/calendar-item.html
- src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
sync icon is next to checkbox for external events in sidebar.
go to calendar module, check that the icon appears. if you click on it you should get a timeout for the following route in the network:
http://localdev:8090/calendar/[[yourCalendar]]/ical?url=[[yourUrl]]
#MC-203 https://jira.support-ent.fr/browse/MC-203
> feat(sidebar): #MC-203 add sync button to external calendars

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
- src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.html
- src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
change external calendar form view
add label to selector
take selection into account to (dis)able the save button
open form, see if label is displayed in selector, 
then check how the save button reacts depending on which fields are filled (should be activated if all fields are used only)
#MC-167 https://jira.support-ent.fr/browse/MC-167
> fix(view): #MC-167 fix external calendar form

- src/main/resources/public/template/view-event.html
warning does not appear when viewing external event
open external event and check if warning is not there
#MC-169 https://jira.support-ent.fr/browse/MC-169
> fix(event): #MC-169 remove warning in event view for external events

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/sass/global/components/sidebar.scss
- src/main/resources/public/ts/directives/calendar-item/calendar-item.html
- src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
- src/main/resources/public/ts/model/Calendar.ts
- src/main/resources/public/ts/utils/date.utils.ts
add tooltip that displays external calendar's last update
place mouse over external calendar in sidebar and check tooltip
#MC-206 https://jira.support-ent.fr/browse/MC-206
> feat(tooltip): #MC-206 add last update in external calendar tooltip

- src/main/resources/public/sass/global/_calendar-specifics.scss
- src/main/resources/public/sass/global/components/_icons.scss
change font-family name
[MC-203](https://jira.support-ent.fr/browse/MC-203)
> fix(css): #MC-203 rename font family

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/controllers/EventController.java
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/core/constants/Rights.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/services/CalendarService.java
- src/main/java/net/atos/entng/calendar/services/EventServiceMongo.java
- src/main/java/net/atos/entng/calendar/services/ServiceFactory.java
- src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
- src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
the following actions cannot be applied to external calendars/events of external calendars
For the events:
creation 
editions
deletion
sharing 
For the calendars:
import 
export 
sharing 
try to call apis with postman
[MC-204](https://jira.support-ent.fr/browse/MC-204)
> feat(api): #MC-204 secure API endpoints

- src/main/resources/public/template/top-menu.html
Change class rbs to calendar
[MC-222](https://jira.support-ent.fr/browse/MC-222)
> fix(html) #MC-222 correct class in html

- src/main/resources/public/sass/global/components/_icons.scss
Add font-family to icons
[MC-202](https://jira.support-ent.fr/browse/MC-202)
> fix(icons) #MC-202 add font-family to icons

- build.gradle
- src/main/java/net/atos/entng/calendar/Calendar.java
- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/core/constants/Actions.java
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/core/constants/Rights.java
- src/main/java/net/atos/entng/calendar/core/enums/ExternalICalEventBusActions.java
- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
- src/main/java/net/atos/entng/calendar/ical/ExternalImportICal.java
- src/main/java/net/atos/entng/calendar/services/CalendarService.java
- src/main/java/net/atos/entng/calendar/services/EventServiceMongo.java
- src/main/java/net/atos/entng/calendar/services/ServiceFactory.java
- src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
- src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
it is possible to get events from calendar body with ics url
Documentation: 
https://confluence.support-ent.fr/pages/viewpage.action?pageId=107217461
io.vertx:vertx-web-client: 3.9.5
used to download the content of and URL
call API with the right body using postman
[MC-184](https://jira.support-ent.fr/browse/MC-184)
> feat(sync): #MC-184 get and save calendar + events from url

- src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.html
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
- src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.html
- src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
- src/main/resources/public/ts/model/Calendar.ts
- src/main/resources/public/ts/model/calendar-form.model.ts
- src/main/resources/public/ts/services/calendar.service.ts
- src/main/resources/public/ts/utils/externalCalendarUtils.ts
- update front so that routes match with the back-end
- no more platform field
fill form and submit : there should be no "platform" selection and route should be calendar/url
click on "sync" button : route should be calendar/:id/url
[MC-219](https://jira.support-ent.fr/browse/MC-219)
> fix(url): #MC-219 update front code and API routes

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/core/constants/MongoField.java
- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
- src/main/java/net/atos/entng/calendar/ical/ExternalImportICal.java
- src/main/java/net/atos/entng/calendar/ical/ICalHandler.java
- src/main/java/net/atos/entng/calendar/services/EventServiceMongo.java
- src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
- src/main/java/net/atos/entng/calendar/utils/DateUtils.java
Allow to synchronize an external calendar (previously imported for the first time). **All events since the last update** are deleted and then recreated. 
Call API using the id of an external event
[MC-171](https://jira.support-ent.fr/browse/MC-171)
> feat(sync): #MC-171 sync external events from url

- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
'isUpdating' field switches to false when update has succeeded
check database after update call with 200 response
[MC-171](https://jira.support-ent.fr/browse/MC-171)
> fix(sync): #MC-171 fix update field does not become false when succeed

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/core/constants/Actions.java
- src/main/java/net/atos/entng/calendar/core/constants/Rights.java
- src/main/java/net/atos/entng/calendar/services/CalendarService.java
- src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
allow user to make requests to get his own calendars
call API with postman and valid calendar id
[MC-234](https://jira.support-ent.fr/browse/MC-234)
> feat(update): #MC-234 create API to get calendar by id

- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
update field is changed AT THE END of a successful sync of the external calendar
call sync route with postman
[MC-171](https://jira.support-ent.fr/browse/MC-171)
> fix(sync): #MC-171 fix update field change in flow

- src/main/java/net/atos/entng/calendar/controllers/EventController.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
allow to delete events from external calendar if the latter is deleted too
call API with postman
new optional parameter added in doc:
[MC-240](https://jira.support-ent.fr/browse/MC-240)
> feat(delete): #MC-240 allow external event deletion if calendar is also deleted

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
Change API route
[MC-234](https://jira.support-ent.fr/browse/MC-234)
> fix(update): #MC-234 create API to get calendar by id

- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
original delete is kept
[MC-240](https://jira.support-ent.fr/browse/MC-240)
> fix(delete): #MC-240 allow external event deletion if calendar is also deleted

- src/main/resources/public/template/main-view.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/core/enum/platform.enum.ts
- src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
- src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
- src/main/resources/public/ts/directives/side-bar/side-bar.html
- src/main/resources/public/ts/directives/side-bar/side-bar.ts
- src/main/resources/public/ts/services/calendar-event.service.ts
- src/main/resources/public/ts/services/calendar.service.ts
front end of the app is updated after sync
sync and see if :
- the calendar update hour is right
- the events are updated
[MC-188](https://jira.support-ent.fr/browse/MC-188)
> feat(view): #MC-188 update view after sync

- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
[MC-248](https://jira.support-ent.fr/browse/MC-248)
> fix(sync): #MC-243 add default TTL

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
add object to platform and TTL error responses to differentiate them
[MC-168](https://jira.support-ent.fr/browse/MC-168)
> feat(view): #MC-168 differentiate TTL and platform error responses

- build.gradle
- src/test/java/net/atos/entng/calendar/services/CalendarServiceImplTest.java
- src/test/java/net/atos/entng/calendar/services/EventServiceMongoImplTest.java
Added some unit test for MC-171 and MC-184 changes.
Added powermock dependencies for tests
[MC-241](https://jira.support-ent.fr/browse/MC-241)
[MC-184](https://jira.support-ent.fr/browse/MC-184)
[MC-171](https://jira.support-ent.fr/browse/MC-171)
> test(sync): #MC-241 added test for calendar synchronisation

- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
toasters indicate if processes were successful
try to update and create external calendars and check the toaster responses
[MC-168](https://jira.support-ent.fr/browse/MC-168)
> feat(view): #MC-168 add response toasters

- src/main/java/net/atos/entng/calendar/ical/ExternalImportICal.java
no more event switches between calendars
reload calendar page and see if events change calendar
[MC-233](https://jira.support-ent.fr/browse/MC-233)
> fix(sync): #MC-233 fix sync data exchange

- src/main/resources/public/template/main-view.html
- src/main/resources/public/template/top-menu.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/directives/side-bar/side-bar.html
- src/main/resources/public/ts/directives/side-bar/side-bar.ts
- src/main/resources/public/ts/utils/externalCalendarUtils.ts
external calendar features appear only if user has the right to use it
set rights in "access with creation" using admc account
try to connect with admin and student account, the features should not appear in the latter
[MC-235](https://jira.support-ent.fr/browse/MC-235)
> feat(sync): #MC-235 add sync rights in front-end

- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
checks if isExternal is not true instead of false
try to import an ics file
[MC-261](https://jira.support-ent.fr/browse/MC-261)
> feat(sync): #MC-261 fix ics import

- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
- src/main/java/net/atos/entng/calendar/utils/DateUtils.java
when updating external calendar, events in the next hour are deleted before being creating again.
create a google event that starts in less than an hour and sync. Event should not be duplicated sith multiple syncs.
[MC-262](https://jira.support-ent.fr/browse/MC-262)
> fix(sync): #MC-262 fix sync deletion timezone interference

- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
- src/main/java/net/atos/entng/calendar/services/CalendarService.java
- src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
Update time does not change if it failed
update calendar with wronng url, update time should not change
[MC-238](https://jira.support-ent.fr/browse/MC-238)
> fix(sync): #MC-238 do not update field if sync fails

- src/main/resources/public/ts/utils/__test__/date.utils.test.ts
- src/main/resources/public/ts/utils/date.utils.ts
fix ttl tooltip
try to update the calendar too soon.
[MC-258](https://jira.support-ent.fr/browse/MC-258)
> fix(toast): #MC-258 edit TTL tooltip

- src/main/resources/public/ts/controllers/controller.ts
the calendar you choose is the calendar in which ics file is imported
try to import .ics files in various calendars.
[MC-258](https://jira.support-ent.fr/browse/MC-258)
> fix(import): #MC-157 import is in selected calendar

- package.json
- src/main/resources/public/ts/ics-export.ts
update typescript version and adapt code
export calendar on microsoft edge
[MC-271](https://jira.support-ent.fr/browse/MC-271)
> feat(typescript) : #MC-271 update typescript version and adapt code

- deployment/calendar/conf.j2
- deployment/calendar/conf.json.template
- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/core/enums/ExternalICalEventBusActions.java
- src/main/java/net/atos/entng/calendar/helpers/FutureHelper.java
- src/main/java/net/atos/entng/calendar/helpers/PlatformHelper.java
- src/main/java/net/atos/entng/calendar/helpers/StringsHelper.java
Platform and url are checked before creating external calendar
call api with object :
```
{
"title" : "Test",
"color" : "grey",
"isExternal" : true,
"platform" : "Zimbra"
}
```
[MC-260](https://jira.support-ent.fr/browse/MC-260)
> feat(zimbra) : #MC-260 check if external calendar has platform

- src/main/java/net/atos/entng/calendar/helpers/PlatformHelper.java
- src/main/java/net/atos/entng/calendar/helpers/UserHelper.java
when creating an external calendar we check if the user has the desired app in their apps.
call api with object :
```
{
"title" : "Test",
"color" : "grey",
"isExternal" : true,
"platform" : "Zimbra"
}
```
[MC-259](https://jira.support-ent.fr/browse/MC-259)
> feat(zimbra) : #MC-259 check if user has app

- src/main/java/net/atos/entng/calendar/core/enums/ExternalICalEventBusActions.java
- src/main/java/net/atos/entng/calendar/core/enums/ExternalPlatformEnum.java
- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
- src/main/java/net/atos/entng/calendar/helpers/PlatformHelper.java
when sync is called, if the calendar is from a specific platform an eb is sent to the platform
sync calendar with platform
[MC-266](https://jira.support-ent.fr/browse/MC-266)
> feat(zimbra) : #MC-266 call eb when sync platform

- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
receive object from Zimbra eb
[MC-263](https://jira.support-ent.fr/browse/MC-263)
> feat(zimbra): #MC-263 receive eb from Zimbra

- build.gradle
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
- src/main/java/net/atos/entng/calendar/models/CalendarModel.java
- src/test/java/net/atos/entng/calendar/helper/CalendarHelperTest.java
receieved ical is used to create events
[MC-268](https://jira.support-ent.fr/browse/MC-268)
> feat(zimbra): #MC-268 create events from external platform

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/template/top-menu.html
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.html
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
- src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.html
- src/main/resources/public/ts/directives/external-calendar-form/external-calendar-form.ts
- src/main/resources/public/ts/model/Calendar.ts
- src/main/resources/public/ts/model/calendar-form.model.ts
- src/main/resources/public/ts/utils/i18n.utils.ts
- src/main/resources/view-src/calendar.html
new external calendar lightbox with zimbra option
click on "add external calendar button"
[MC-265](https://jira.support-ent.fr/browse/MC-265)
> feat(zimbra): #MC-265 edit external calendar lightbox

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/helpers/PlatformHelper.java
- src/main/java/net/atos/entng/calendar/services/ServiceFactory.java
- src/test/java/net/atos/entng/calendar/helper/CalendarHelperTest.java
- src/test/java/net/atos/entng/calendar/helper/PlatformHelperTest.java
Unit tests to secure helpers
[MC-272](https://jira.support-ent.fr/browse/MC-272)
> fix(zimbra): #MC-272 add unit tests

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/core/enums/ErrorEnum.java
- src/main/java/net/atos/entng/calendar/helpers/CalendarHelper.java
- src/main/java/net/atos/entng/calendar/helpers/EventBusHelper.java
- src/main/java/net/atos/entng/calendar/models/CalendarModel.java
- src/main/java/net/atos/entng/calendar/services/CalendarService.java
- src/main/java/net/atos/entng/calendar/services/impl/CalendarServiceImpl.java
- src/main/resources/i18n/en.json
- src/main/resources/i18n/fr.json
- src/main/resources/public/ts/directives/external-calendar-addition/external-calendar-addition.ts
adapt ical import clos to zimbra queue
[MC-283](https://jira.support-ent.fr/browse/MC-283)
> feat(zimbra): #MC-283 adapt flow to zimbra queue

- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/services/impl/DefaultUserServiceImpl.java
- src/test/java/net/atos/entng/calendar/services/DefaultUserServiceImplTest.java
change ids list usage for neo4j request to remove potential security breaches in the future
Try to download an attachment file within a shared event with a user who is not the owner of this event (so create an event, share with someone, put an attachment file on it, log on the person who got the event shared to, and try to download the attachment).
[MC-286](https://jira.support-ent.fr/browse/MC-286)
> feat(user): #MC-286 change ids list usage for neo4j request

- src/main/resources/public/ts/controllers/controller.ts
shared calendar events are displayed when their calendar is selected for the 1st time
User 1 shares calendar that has events in this current week with user 2.
Log in with user 2, select shared calendar --> the events should appear.
[MC-274](https://jira.support-ent.fr/browse/MC-274)
> fix(share): #MC-274 display events when shared calendar is selected

- src/main/resources/public/ts/controllers/controller.ts
fixed the following case : if calendar is unselected and the user logs out, next time it will still be selected
unselect calendar, log out, log in --> calendar should still be unselected
[MC-104](https://jira.support-ent.fr/browse/MC-104)
> fix(preferences): #MC-104 fix calendar unselection

- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/directives/calendar-item/calendar-item.ts
Preferences stay the same after the following actions on calendars:
- creation
- update
- deletion
Create/update/delete calendars --> selected calendar should not change
> fix(preferences): #MC-73 fix calendar preferences after actions

- src/main/java/net/atos/entng/calendar/controllers/CalendarController.java
fix calendar sharing notification
create calendar & share with another user --> user should get a notification with a full phrase :
> fix(notifications): #MC-215 fix calendar sharing notification

- src/main/java/net/atos/entng/calendar/services/impl/EventServiceMongoImpl.java
Restricted events in shared calendars now only appear to the people they are restricted to
- share calendar to user A
- create event in calendar
- share (restrict) event to user B
--> user A should no see the event and user B should see it
[MC-255](https://jira.support-ent.fr/browse/MC-255)
> fix(restriction): #MC-255 fix shared event restriction

- .github/workflows/dev-check-repository.yml
- .gitignore
- build.sh
- docker-compose.yml
- gulpfile.js
- jest.config.js
- package.json
- src/main/resources/public/sass/global/components/calendar.scss
- src/main/resources/public/sass/global/components/timepicker.scss
- src/main/resources/public/sass/index.scss
- src/main/resources/view-src/calendar.html
Migrate css from entcore-css-lib
[MC-293](https://jira.support-ent.fr/browse/MC-293)
> chore(css): #MC-293 infra-front migration

- src/main/resources/public/ts/controllers/controller.ts
In controller.ts, we changed the search of unique event from iteration filtering to a Map check which is more optimize and prevent from double values.
Now, even if the event has a hundred year's length, the applcation is reachable and works.
Create a 100 year event and try to navigate through the application.
[MC-296](https://jira.support-ent.fr/browse/MC-296)
> fix(calendarEvent): #MC-296 cherry pick Edifice commit to handle long events"

- docker-compose.yml
- gradle.properties
- src/main/java/net/atos/entng/calendar/controllers/EventController.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/utils/DateUtils.java
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/public/ts/model/constantes/actions.const.ts
Ajout d'une nouvelle route afin de mettre à jour toutes les occurrences d'un même événement d'un seul coup.
Au niveau du service, on passe par une commande d'aggrégation plutôt qu'un update afin de pouvoir mettre à jour de façon efficace tous les événements ayant le même parentId tout en gérant la date et l'heure des événements.
WB-2320
> [EDIFICE] use new endpoint to update all recurrent events at once

- deployment/calendar/migration/4.1.0/putDivsAroundDescription.js
- src/main/resources/public/sass/global/components/_edit-event.scss
- src/main/resources/public/template/edit-event.html
- src/main/resources/public/template/main-view.html
- src/main/resources/public/template/view-event.html
- src/main/resources/public/ts/controllers/controller.ts
add editor to calendarEvent description
[MC-308](https://jira.support-ent.fr/browse/MC-308)
> feat(editor): #MAG-308 add editor to calendarEvent description

- package.json
- pom.xml
- src/main/java/net/atos/entng/calendar/controllers/EventController.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/utils/DateUtils.java
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/public/ts/model/constantes/actions.const.ts
Changes from develop b2school for version WB 6.3.0
> Changes from develop b2school for version WB 6.3.0

- src/main/java/net/atos/entng/calendar/Calendar.java
- src/main/java/net/atos/entng/calendar/controllers/ReminderController.java
- src/main/java/net/atos/entng/calendar/core/constants/Actions.java
- src/main/java/net/atos/entng/calendar/core/constants/Field.java
- src/main/java/net/atos/entng/calendar/core/constants/MongoField.java
- src/main/java/net/atos/entng/calendar/core/constants/Rights.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/helpers/ReminderHelper.java
- src/main/java/net/atos/entng/calendar/helpers/WorkflowHelper.java
- src/main/java/net/atos/entng/calendar/models/OwnerModel.java
- src/main/java/net/atos/entng/calendar/models/User.java
- src/main/java/net/atos/entng/calendar/models/reminders/ReminderFrontEndModel.java
- src/main/java/net/atos/entng/calendar/models/reminders/ReminderModel.java
- src/main/java/net/atos/entng/calendar/security/ViewRight.java
- src/main/java/net/atos/entng/calendar/services/ReminderService.java
- src/main/java/net/atos/entng/calendar/services/impl/ReminderServiceImpl.java
- src/main/java/net/atos/entng/calendar/utils/ReminderConverter.java
- src/main/resources/public/ts/controllers/controller.ts
- src/main/resources/public/ts/directives/calendarevent-reminder-form/calendarevent-reminder-form.ts
- src/main/resources/public/ts/model/CalendarEvent.ts
- src/main/resources/public/ts/model/index.ts
- src/main/resources/public/ts/model/reminder.model.ts
- src/main/resources/public/ts/services/calendar-event.service.ts
- src/main/resources/public/ts/services/index.ts
- src/main/resources/public/ts/services/reminder.service.ts
user can create edit and delete reminder from both edit event and view event layouts
try all 3 actions for both cases
[MC-312](https://jira.support-ent.fr/browse/MC-312)
> feat(reminder): #MC-312 implement reminder creation edition deletion

- build.sh
- src/main/resources/public/sass/global/components/additional.scss
[MC-308](https://jira.support-ent.fr/browse/MC-308)
> chore(css): add css compilation in buildNode

- src/main/java/net/atos/entng/calendar/helpers/ReminderHelper.java
- src/main/java/net/atos/entng/calendar/services/impl/ReminderServiceImpl.java
- src/main/java/net/atos/entng/calendar/utils/ReminderConverter.java
- src/main/resources/i18n/timeline/en.json
- src/main/resources/i18n/timeline/fr.json
- src/main/resources/view-src/notify/calendar/reminder.html
[MC-318](https://jira.support-ent.fr/browse/MC-318)
> fix(reminders): #MC-318 fix reminders after testing feedback

- src/main/java/net/atos/entng/calendar/core/constants/Actions.java
- src/main/java/net/atos/entng/calendar/helpers/EventHelper.java
- src/main/java/net/atos/entng/calendar/helpers/ReminderHelper.java
- src/main/java/net/atos/entng/calendar/utils/ReminderConverter.java
[MC-317](https://jira.support-ent.fr/browse/MC-317)
> fix(updateRecurrence): #MC-317 fix reminders when updating all recurrence
